"""
Allomorph - Digital Signal Processing & Filter Synthesis Subpackage.
Provides high-performance NumPy-vectorized and Numba-accelerated DSP engines,
homomorphic real-cepstrum Hilbert transform FIR synthesis, ITU-R BS.1770-4 loudness
measurement, and 24-bit PCM audio export.
"""

from allomorph.dsp.conditioning import (
    CALIBRATION_PEAK_CEILING,
    apply_calibrated_normalization,
    apply_dc_block,
    apply_johnson_dither,
    get_white_noise_vector,
)
from allomorph.dsp.constants import (
    AUDIO_DIR,
    DEFAULT_INPUT_PATH,
    FREQS,
    FS,
    NUM_TAPS,
    NYQ,
    REPO_ROOT,
    _apply_cinf_fades,
    _cinf_smoothstep,
    apply_biquad,
    apply_cinf_fades,
    cinf_smoothstep,
)
from allomorph.dsp.convolution import (
    calibrate_nam_v3_latency,
    fft_convolve,
    fft_convolve_multi,
)
from allomorph.dsp.dry import (
    ensure_input_audio_wav,
    generate_input_audio,
    generate_optimal_bass_dry,
    synth_articulation_bursts,
    synth_calibration_blips,
    synth_glissandi_slides,
    synth_log_chirps,
    synth_long_ringouts,
    synth_modal_plucks,
    synth_polyphony_and_probes,
    synth_velocity_ladder,
)
from allomorph.dsp.fir import (
    compute_minimum_phase_spectrum,
    synthesize_minimum_phase_fir,
    window_fir_impulse,
)
from allomorph.dsp.io import (
    compute_true_peak,
    compute_true_peak_dbfs,
    read_wav,
    read_wav_24bit,
    write_wav_24bit,
)
from allomorph.dsp.loudness import (
    apply_itu_gating,
    apply_k_weighting_filter,
    compute_gated_loudness_blocks,
    compute_lufs,
)
from allomorph.dsp.plucks import (
    _calc_inharmonicity_b,
    _synth_dyad,
    _synth_ghost_note,
    _synth_ghost_rake,
    _synth_glissando,
    _synth_groove_burst,
    _synth_long_ringout,
    _synth_natural_harmonic,
    _synth_pluck,
    _synth_slap_pop_pair,
    _synth_two_tone_probe,
    _synth_vibrato_pluck,
    apply_attack_pitch_sag,
    apply_fret_buzz_nonlinearity,
    compute_modal_frequencies,
    generate_exponential_ringout_envelope,
)
from allomorph.dsp.sweeps import (
    _synth_log_chirp,
    deconvolve_log_sweep,
    extract_farina_harmonics,
    synthesize_fast_log_sweep,
)

__all__ = [
    "AUDIO_DIR",
    "CALIBRATION_PEAK_CEILING",
    "DEFAULT_INPUT_PATH",
    "FREQS",
    "FS",
    "NUM_TAPS",
    "NYQ",
    "REPO_ROOT",
    "_apply_cinf_fades",
    "_calc_inharmonicity_b",
    "_cinf_smoothstep",
    "_synth_dyad",
    "_synth_ghost_note",
    "_synth_ghost_rake",
    "_synth_glissando",
    "_synth_groove_burst",
    "_synth_log_chirp",
    "_synth_long_ringout",
    "_synth_natural_harmonic",
    "_synth_pluck",
    "_synth_slap_pop_pair",
    "_synth_two_tone_probe",
    "_synth_vibrato_pluck",
    "apply_attack_pitch_sag",
    "apply_biquad",
    "apply_calibrated_normalization",
    "apply_cinf_fades",
    "apply_dc_block",
    "apply_fret_buzz_nonlinearity",
    "apply_itu_gating",
    "apply_johnson_dither",
    "apply_k_weighting_filter",
    "calibrate_nam_v3_latency",
    "cinf_smoothstep",
    "compute_gated_loudness_blocks",
    "compute_lufs",
    "compute_minimum_phase_spectrum",
    "compute_modal_frequencies",
    "compute_true_peak",
    "compute_true_peak_dbfs",
    "deconvolve_log_sweep",
    "ensure_input_audio_wav",
    "extract_farina_harmonics",
    "fft_convolve",
    "fft_convolve_multi",
    "generate_exponential_ringout_envelope",
    "generate_input_audio",
    "generate_optimal_bass_dry",
    "get_white_noise_vector",
    "read_wav",
    "read_wav_24bit",
    "synth_articulation_bursts",
    "synth_calibration_blips",
    "synth_glissandi_slides",
    "synth_log_chirps",
    "synth_long_ringouts",
    "synth_modal_plucks",
    "synth_polyphony_and_probes",
    "synth_velocity_ladder",
    "synthesize_fast_log_sweep",
    "synthesize_minimum_phase_fir",
    "window_fir_impulse",
    "write_wav_24bit",
]
